language: csharp
solution: src/CiSampleNetCore/CiSampleNetCore.sln

before_install: 
  - sudo pip install codecov
  
install:
  - sudo apt-get install mono-devel nunit-console       
   
script: 
  - xbuild src/CiSampleNetCore/01-Apps/WebCore/WebCore.csproj

after_success: 
  - codecov
