language: csharp
solution: src/CiSampleNetCore/CiSampleNetCore.sln
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1

before_install: 
  - sudo pip install codecov

before_script:
 - chmod +x ./build.sh
 
script: 
  - ./build.sh  

after_success: 
  - codecov
